import { HullGenerator } from './viewer/HullGenerator.js';
import { HullSurface } from './viewer/HullSurface.js';
import { makeStations } from './viewer/StationGenerator.js';
import { makeWaterlines } from './viewer/WaterlineGenerator.js';
import { CameraManager } from './viewer/CameraManager.js';
import { SectionViewer } from './viewer/SectionViewer.js';
import { renderMeasurements } from './viewer/MeasurementOverlay.js';
import { ExportManager } from './viewer/ExportManager.js';
import { bindToolbar } from './viewer/ViewerToolbar.js';
import { RendererManager } from './viewer/RendererManager.js';
import { SceneManager } from './viewer/SceneManager.js';
import { GridManager } from './viewer/GridManager.js';
import { OrientationCube } from './viewer/OrientationCube.js';

const T=window.THREE;
const num=(id,fallback)=>{const n=Number(document.getElementById(id)?.value);return Number.isFinite(n)&&n>0?n:fallback;};
const log=message=>console.info('[Hull Viewer] '+message);
function validateGeometry(geometry){geometry.computeBoundingBox();geometry.computeBoundingSphere();const positions=geometry.getAttribute('position'),box=geometry.boundingBox,sphere=geometry.boundingSphere;const finite=box&&sphere&&[box.min.x,box.min.y,box.min.z,box.max.x,box.max.y,box.max.z,sphere.radius].every(Number.isFinite);if(!positions||positions.count===0||!finite||sphere.radius<=0)throw new Error('Generated hull geometry has invalid vertices or bounds.');console.table({vertices:positions.count,triangles:geometry.index?geometry.index.count/3:positions.count/3,bbox:`${box.min.toArray().join(', ')} → ${box.max.toArray().join(', ')}`,center:sphere.center.toArray().join(', '),radius:sphere.radius,meshScale:box.getSize(new T.Vector3()).toArray().join(', ')});return geometry;}
function fallbackGeometry(){const g=new T.BoxGeometry(20,5,5);g.computeVertexNormals();g.computeBoundingBox();g.computeBoundingSphere();return g;}
class ProfessionalHullViewer {
  constructor(el){this.el=el;this.sceneManager=new SceneManager();this.scene=this.sceneManager.scene;log('Scene created');log('Lights created');this.rendererManager=new RendererManager(el);this.renderer=this.rendererManager.renderer;log('Renderer created');this.dirty=false;this.firstRender=true;this.status=this.makeStatus();this.camera=new CameraManager(this.renderer,el,()=>this.render());log('Camera created');log('OrbitControls created (CameraManager orbit controls)');this.gridManager=new GridManager();this.grid=this.gridManager.grid;this.axes=this.gridManager.axes;this.scene.add(this.gridManager.group);this.orientation=new OrientationCube();this.scene.add(this.orientation.group);if(window.__HULL_VIEWER_DIAGNOSTIC__){this.cameraHelper=new T.CameraHelper(this.camera.camera);this.scene.add(this.cameraHelper);log('AxesHelper, GridHelper and CameraHelper added');}new ResizeObserver(()=>this.resize()).observe(el);this.rebuild();}
  data(){return {lpp:num('lpp',100),lwl:num('lwl',102),beam:num('beam',18),draft:num('draft',5.5),cb:num('cb',.70),cm:num('cm',.98),cwp:num('cwp',.80),lcb:Number(document.getElementById('lcb')?.value)||0};}
  makeStatus(){const n=document.createElement('div');n.className='hull-status';this.el.appendChild(n);return n;}
  showStatus(message,error=false){this.status.textContent=message;this.status.classList.toggle('error',error);this.status.hidden=!message;}
  rebuild(){this.showStatus('Initializing…');try{this.d=this.data();log('Vessel inputs loaded');if(this.group)this.scene.remove(this.group);if(this.section?.line)this.scene.remove(this.section.line);this.group=new T.Group();this.showStatus('Generating Hull…');log('Hull generation started');this.generator=new HullGenerator(this.d,120,80);let geometry;try{geometry=window.__HULL_VIEWER_DIAGNOSTIC__?new T.BoxGeometry(20,5,5):this.generator.build();geometry=validateGeometry(geometry);log('Hull generation finished');}catch(error){console.error('Hull generator failed; using fallback geometry.',error);geometry=validateGeometry(fallbackGeometry());this.showStatus('Hull generation failed. Displaying fallback geometry.');}this.showStatus('Computing Mesh…');this.surface=new HullSurface(geometry);if(window.__HULL_VIEWER_NORMAL_PROBE__)this.surface.mesh.material=new T.MeshNormalMaterial();log('Mesh created');this.group.add(this.surface.mesh,this.surface.wire);this.stations=makeStations(this.generator);this.waterlines=makeWaterlines(this.generator);this.buttocks=this.makeButtocks();this.references=this.makeReferences();this.group.add(this.stations,this.waterlines,this.buttocks,this.references);this.scene.add(this.group);log('Mesh added to scene');this.section=new SectionViewer(this.surface,this.generator,this.scene);this.section.set(Number(document.getElementById('stationSlider')?.value||50));this.camera.fit(geometry.boundingBox.clone());log('Camera fitted');renderMeasurements(this.d);this.showStatus('Ready');setTimeout(()=>this.showStatus(''),700);this.render();}catch(error){console.error('Hull viewer setup failed:',error);this.showStatus('Hull generation failed',true);this.render();}}
  makeButtocks(){const g=new T.Group();[-.6,-.3,0,.3,.6].forEach(f=>{const p=[];for(let i=0;i<=this.generator.stations;i++){const u=i/this.generator.stations,b=this.generator.breadth(u);p.push(new T.Vector3((u-.5)*this.d.lpp,b*f,this.d.draft*.02));}g.add(new T.Line(new T.BufferGeometry().setFromPoints(p),new T.LineBasicMaterial({color:0x669bb8,transparent:true,opacity:.55})));});return g;}
  makeReferences(){const g=new T.Group(),line=(a,b,c)=>g.add(new T.Line(new T.BufferGeometry().setFromPoints([a,b]),new T.LineBasicMaterial({color:c}))),d=this.d,L=d.lpp/2,z0=-d.draft*.5,z1=d.draft*.5;line(new T.Vector3(-L,0,z0),new T.Vector3(L,0,z0),0xd8e2e9);line(new T.Vector3(-L,0,z1),new T.Vector3(L,0,z1),0x95d9ef);line(new T.Vector3(-L,-d.beam*.6,z0),new T.Vector3(-L,-d.beam*.6,z1*1.2),0xe4e8ec);line(new T.Vector3(L,-d.beam*.6,z0),new T.Vector3(L,-d.beam*.6,z1*1.2),0xe4e8ec);line(new T.Vector3(0,-d.beam*.6,z0),new T.Vector3(0,-d.beam*.6,z1*1.2),0xffd166);const water=new T.Mesh(new T.PlaneGeometry(d.lpp*1.2,d.beam*2),new T.MeshBasicMaterial({color:0x3e9ac3,transparent:true,opacity:.12,side:T.DoubleSide}));water.position.z=z1;g.add(water);return g;}
  layer(name,on){const map={surface:this.surface?.mesh,wireframe:this.surface?.wire,stations:this.stations,buttocks:this.buttocks,waterlines:this.waterlines,grid:this.grid,axes:this.axes,labels:this.references,bounds:this.surface?.wire};if(map[name])map[name].visible=on;this.render();}
  action(a){if(a==='reset')this.camera.fit(new T.Box3().setFromObject(this.surface.mesh));if(a==='camera')this.camera.setOrtho(!this.camera.orthographic);if(a==='wireframe')this.layer('wireframe',!this.surface.wire.visible);if(a==='screenshot')this.exports.screenshot();if(a==='fullscreen')this.el.parentElement.requestFullscreen?.();if(a==='grid')this.layer('grid',!this.grid.visible);if(a==='labels')this.layer('stations',!this.stations.visible);this.render();}
  resize(){const w=this.el.clientWidth,h=this.el.clientHeight;if(!w||!h)return;this.rendererManager.resize(w,h);this.camera.resize(w,h);this.render();}
  render(){if(this.dirty)return;this.dirty=true;requestAnimationFrame(()=>{this.dirty=false;this.orientation.update(this.camera.camera);if(this.cameraHelper)this.cameraHelper.update();this.renderer.render(this.scene,this.camera.camera);if(this.firstRender){this.firstRender=false;log('First render complete');}});}
}
function init(){const el=document.getElementById('hullViewer');if(!el)return;if(!T){console.error('[Hull Viewer] Three.js failed to load');const error=document.createElement('div');error.className='hull-status error';error.textContent='Hull generation failed';el.appendChild(error);return;}const v=window.hullViewer=new ProfessionalHullViewer(el);v.exports=new ExportManager(v);bindToolbar(v);document.querySelectorAll('.hull-panel h3').forEach(h=>{h.tabIndex=0;h.title='Toggle card';h.addEventListener('click',()=>{const body=h.nextElementSibling;if(body)body.hidden=!body.hidden;});});['lpp','lwl','beam','draft','cb','cm','cwp','lcb','abt','hb','at'].forEach(id=>document.getElementById(id)?.addEventListener('change',()=>v.rebuild()));const slider=document.getElementById('stationSlider');slider?.addEventListener('input',e=>{v.section.set(Number(e.target.value));document.getElementById('stationValue').value=e.target.value+'%';v.render();});document.getElementById('hullOpacity')?.addEventListener('input',e=>{v.surface.opacity=Number(e.target.value)/100;document.getElementById('hullOpacityValue').value=e.target.value+'%';v.render();});document.getElementById('stationAnimateBtn')?.addEventListener('click',()=>{if(v.timer){clearInterval(v.timer);v.timer=null;return;}v.timer=setInterval(()=>{slider.value=(Number(slider.value)+1)%101;slider.dispatchEvent(new Event('input'));},45);});}
document.addEventListener('DOMContentLoaded',init);
