const T=window.THREE;
export class CameraManager {
  constructor(renderer,el,change){this.el=el;this.change=change;this.target=new T.Vector3();this.theta=Math.PI/4;this.phi=Math.acos(1/Math.sqrt(3));this.radius=100;this.orthographic=false;this.camera=new T.PerspectiveCamera(45,1,.01,10000);this.bind(renderer.domElement);}
  bind(el){let drag=null;const end=()=>{drag=null;this.change();};el.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,pan:e.button===2};el.setPointerCapture(e.pointerId)});el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end);el.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.x=e.clientX;drag.y=e.clientY;if(drag.pan){const r=new T.Vector3().setFromMatrixColumn(this.camera.matrix,0),u=new T.Vector3().setFromMatrixColumn(this.camera.matrix,1);this.target.addScaledVector(r,-dx*this.radius/700).addScaledVector(u,dy*this.radius/700)}else{this.theta-=dx*.008;this.phi=Math.max(.03,Math.min(Math.PI-.03,this.phi-dy*.008))}this.update()});el.addEventListener('wheel',e=>{e.preventDefault();this.radius=Math.max(.5,Math.min(10000,this.radius*Math.exp(e.deltaY*.001)));this.update()},{passive:false});el.addEventListener('contextmenu',e=>e.preventDefault());}
  fit(box){if(box.isEmpty())throw new Error('The generated hull has no visible bounds.');const sphere=box.getBoundingSphere(new T.Sphere());this.target.copy(sphere.center);const fov=T.MathUtils.degToRad(this.camera.isPerspectiveCamera?this.camera.fov:45);this.radius=Math.max(sphere.radius/Math.sin(fov/2)*1.18,2);this.camera.near=Math.max(.01,this.radius/100);this.camera.far=Math.max(1000,this.radius*100);this.theta=Math.PI/4;this.phi=Math.acos(1/Math.sqrt(3));this.update();}
  update(){const s=Math.sin(this.phi);this.camera.position.set(this.target.x+this.radius*s*Math.cos(this.theta),this.target.y+this.radius*s*Math.sin(this.theta),this.target.z+this.radius*Math.cos(this.phi));this.camera.lookAt(this.target);this.camera.updateProjectionMatrix();this.change();}
  view(name){const a={iso:[Math.PI/4,Math.acos(1/Math.sqrt(3))],top:[0,.02],side:[0,Math.PI/2],front:[Math.PI/2,Math.PI/2],aft:[-Math.PI/2,Math.PI/2],bottom:[0,Math.PI-.02],section:[.1,Math.PI/2]}[name]||[Math.PI/4,Math.acos(1/Math.sqrt(3))];this.theta=a[0];this.phi=a[1];this.update();}
  setOrtho(on){if(on===this.orthographic)return;const old=this.camera;this.orthographic=on;if(on){const h=this.radius*.75;this.camera=new T.OrthographicCamera(-h,h,h,h,old.near,old.far)}else this.camera=new T.PerspectiveCamera(45,old.aspect,old.near,old.far);this.resize(this.el.clientWidth,this.el.clientHeight);this.update();}
  resize(w,h){if(!w||!h)return;this.camera.aspect=w/h;if(this.camera.isOrthographicCamera){const h2=this.radius*.75;this.camera.left=-h2*w/h;this.camera.right=h2*w/h;this.camera.top=h2;this.camera.bottom=-h2;}this.camera.updateProjectionMatrix();}
}
